### ISSUE TITLE
Inquiring API key fails

### ISSUE THREAD

**Issue by markuskuusisto** [tradingstrategy-ai/trading-strategy#41]
Inquiring API key fails because `setup_on_demand(self, **kwargs)` cannot pack `None`.

```
from tradingstrategy.client import Client
client = Client.create_jupyter_client()
```

```
Traceback (most recent call last):
  File "/trading.py", line 3, in <module>
    client = Client.create_jupyter_client()
  File "/lib/python3.9/site-packages/tradingstrategy/client.py", line 330, in create_jupyter_client
    config = env.setup_on_demand(api_key)
TypeError: setup_on_demand() takes 1 positional argument but 2 were given
```

**Comment by markuskuusisto** [comment]
The issue is not present in the latest code, just with the version in pip.
